name: test
on:
  push:
    branches:
    - master
    - es6
  pull_request:
    branches:
    - master
    - es6
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: make install
    #- run: make eslint
    - run: make test
